CREATE TABLE IF NOT EXISTS weather (
    timezone VARCHAR,
    state_code INTEGER,
    country_code VARCHAR,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    city_name VARCHAR,
    station_id VARCHAR,
    sources VARCHAR,
    city_id INTEGER,
    rh DOUBLE PRECISION,
    wind_spd DOUBLE PRECISION,
    timestamp_utc VARCHAR,
    slp DOUBLE PRECISION,
    vis DOUBLE PRECISION,
    pod VARCHAR,
    solar_rad DOUBLE PRECISION,
    pres DOUBLE PRECISION,
    h_angle DOUBLE PRECISION,
    dewpt DOUBLE PRECISION,
    snow INTEGER,
    uv DOUBLE PRECISION,
    elev_angle DOUBLE PRECISION,
    wind_dir INTEGER,
    ghi DOUBLE PRECISION,
    dhi DOUBLE PRECISION,
    timestamp_local TIMESTAMP,
    dni DOUBLE PRECISION,
    azimuth DOUBLE PRECISION,
    datetime VARCHAR,
    temp DOUBLE PRECISION,
    precip INTEGER,
    clouds INTEGER,
    ts INTEGER,
    weather_icon VARCHAR,
    weather_code INTEGER,
    weather_description VARCHAR,
    PRIMARY KEY (timestamp_local, lat, lon)
);